"""Add firefighter fields

Revision ID: 7e7210e28c27
Revises: b4ea74b83dac
Create Date: 2025-05-13 12:11:29.699995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7210e28c27'
down_revision = 'b4ea74b83dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_firefighter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('firefighter_id', sa.String(length=20), nullable=True))
        batch_op.alter_column('device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['firefighter_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('firefighter_id')
        batch_op.drop_column('is_firefighter')

    # ### end Alembic commands ###
